### PR TITLE
Models

### LINKED ISSUE #13: Model parameter in config file
Add ability to run different models easily by defining them in the config file. Consider multiple approaches from having hard coded models, to dynamically loading model from python file or some other format.

### PR DESCRIPTION
**Pull request by Ceres445**
Resolves #13

### CODE REVIEW

**Comment by Ceres445** [comment]
Added a dumb split that somehow gives 85% accuracy with one epoch on fashionmnist

**Comment by eigengravy** [comment]
> ` stratified_split_dataset` throws an error `AttributeError: 'PlantDataset' object has no attribute 'targets'`, `PlantDataset` is a subclass of `Dataset` , implemented for the new model. Any ideas how to generalise the stratified split

so the inherited class is storing the targets data in labels
 
image

modify the split functions to take the labels/targets a input as well instead of
```    
labels = dataset.targets.tolist()
```

**Comment by eigengravy** [comment]
keep the simple split function in the codebase, will come in handy

**Comment by eigengravy** [comment]
also imo we should couple the dataset and model into a single config variable since a model will usually be for the specific dataset's data structure

**Comment by Ceres445** [comment]
> also imo we should couple the dataset and model into a single config variable since a model will usually be for the specific dataset's data structure

I'm currently hardcoding it as `cur`, could easily move it to config

**Comment by Ceres445** [comment]
image

accuracy seems fine, also I'm using like a very small dataset because my laptop crashes if i increase it. Can be changed from line 26 in `data_generator.py` in the plant_disease submodule

**Review by eigengravy — APPROVED** [review]
lgtm :tada:

**Pull request merged**
